# Indexing, Slicing & Boolean Masking

### Why is this topic crucial for Scikit-Learn? 
When working with machine learning datasets, data rarely enters a model without initial manipulation and filtering: 


- separating the feature matrix ($X$) from the target vector ($y$)—isolating the output column (labels or continuous values) from the input feature columns is the primary use case for slicing; 

- row slicing for initial testing and validation—quickly accessing the first few rows to check dimensions without loading the entire dataset; 

- conditional filtering of samples (Boolean masking)—removing outliers, selecting specific classes, or identifying invalid rows without the need for slow Python loops.

### Key Concepts and Techniques
1. **Direct 2D access** (`array[row, col]`)

In NumPy, accessing a row and column is done within a single pair of brackets:

- `data[0, 0]` returns the value at the first row and first column.

- `data[-1, -1]` returns the value at the last row and last column.

2. **Boolean Masking**:

If you define a condition on an array, NumPy generates an array of the same shape containing `True` and `False` values. By passing this boolean array as an index to the original array, only the elements corresponding to `True` are filtered.

3. **Slicing**:

The colon operator signifies the selection of an index range (start:stop): 

- `X[:, :-1]` refers to all rows and all columns except the last one (the standard form for extracting matrix $X$);

- `X[:, -1]` refers to all rows and only the last column (the standard form for extracting vector $y$); and

- `X[:5, :]` selects the first 5 rows and all columns (similar to `head()` in pandas).

## Code Examples

In [1]:
import numpy as np

# 1. Simulating a dataset: 5 samples, 3 features, 1 target label (Binary: 0 or 1)
raw_dataset = np.array([
    [25.0, 55000.0, 1.2, 0],
    [32.0, 62000.0, 2.5, 1],
    [47.0, 89000.0, 3.1, 1],
    [19.0, 22000.0, 0.8, 0],
    [52.0, 95000.0, 4.0, 1]
])

print("Raw Dataset Shape:", raw_dataset.shape)

# 2. Extracting feature matrix X and target vector y
# X takes all rows and all columns except the last one
X = raw_dataset[:, :-1]

# y takes all rows and only the last column
y = raw_dataset[:, -1]

print("\nFeature Matrix X Shape:", X.shape)
print("Target Vector y Shape:", y.shape)
print("Target Vector contents:", y)

# 3. Slicing specific rows (e.g., first 3 training samples)
subset_X = X[:3, :]
print("\nFirst 3 samples of X:\n", subset_X)

# 4. Boolean Masking: Filter samples where age (column 0) is greater than or equal to 30
age_condition = X[:, 0] >= 30.0
filtered_X = X[age_condition]

print("\nSamples where Age >= 30:\n", filtered_X)

Raw Dataset Shape: (5, 4)

Feature Matrix X Shape: (5, 3)
Target Vector y Shape: (5,)
Target Vector contents: [0. 1. 1. 0. 1.]

First 3 samples of X:
 [[2.5e+01 5.5e+04 1.2e+00]
 [3.2e+01 6.2e+04 2.5e+00]
 [4.7e+01 8.9e+04 3.1e+00]]

Samples where Age >= 30:
 [[3.2e+01 6.2e+04 2.5e+00]
 [4.7e+01 8.9e+04 3.1e+00]
 [5.2e+01 9.5e+04 4.0e+00]]


## Practice

Problem Statement:

Assume the evaluation data for six different machine learning models is stored as follows:
The columns contain, in order: 
[Number of parameters (millions), Training time (seconds), Final accuracy].

In [2]:
import numpy as np

models_data = np.array([
    [12.5, 85.0, 0.78],
    [9.2,  45.0, 0.42],
    [15.1, 92.0, 0.91],
    [8.4,  30.0, 0.35],
    [11.0, 78.0, 0.65],
    [14.3, 88.0, 0.84]
])

1. Split this matrix into two parts using slicing:

- Input variables (`X_models`, comprising the first two columns)

- Model accuracy vector (`y_accuracy`, comprising the third column)

2. Store the first two rows of `X_models` in a separate variable named `baseline_models` using row slicing, and print it.

3. Using the Boolean masking technique, filter the rows of the entire `models_data` matrix where the final accuracy (the third column) is greater than or equal to 0.70.

4. Check the shape of each resulting part.

In [11]:
import numpy as np

# Input dataset: [Parameters (M), Training Time (s), Final Accuracy]
models_data = np.array([
    [12.5, 85.0, 0.78],
    [9.2,  45.0, 0.42],
    [15.1, 92.0, 0.91],
    [8.4,  30.0, 0.35],
    [11.0, 78.0, 0.65],
    [14.3, 88.0, 0.84]
])

# Task 1: Separate features (X) and target metric (y)

# Task 2: Slice the first 2 rows

# Task 3: Filter rows with accuracy >= 0.70 using boolean masking

# Task 4: Verify dimensions

### Answer is

In [4]:
import numpy as np

# Input dataset: [Parameters (M), Training Time (s), Final Accuracy]
models_data = np.array([
    [12.5, 85.0, 0.78],
    [9.2,  45.0, 0.42],
    [15.1, 92.0, 0.91],
    [8.4,  30.0, 0.35],
    [11.0, 78.0, 0.65],
    [14.3, 88.0, 0.84]
])

# Task 1: Separate features (X) and target metric (y)
X_models = models_data[:, :2]
y_accuracy = models_data[:, 2]

print("Features (X_models) Shape:", X_models.shape)
print("Accuracy (y_accuracy) Shape:", y_accuracy.shape)

# Task 2: Slice the first 2 rows
baseline_models = X_models[:2, :]
print("\nBaseline Models (First 2 rows):\n", baseline_models)

# Task 3: Filter rows with accuracy >= 0.70 using boolean masking
high_accuracy_mask = models_data[:, 2] >= 0.70
top_models = models_data[high_accuracy_mask]

print("\nTop Performing Models (Accuracy >= 0.70):\n", top_models)

# Task 4: Verify dimensions
print("\nTop Models Shape:", top_models.shape)

Features (X_models) Shape: (6, 2)
Accuracy (y_accuracy) Shape: (6,)

Baseline Models (First 2 rows):
 [[12.5 85. ]
 [ 9.2 45. ]]

Top Performing Models (Accuracy >= 0.70):
 [[12.5  85.    0.78]
 [15.1  92.    0.91]
 [14.3  88.    0.84]]

Top Models Shape: (3, 3)
