# Using functions to create arrays faster
## Why are these functions important?
When working with Scikit-Learn models, you almost never type the data manually. These functions are used in the following real-world scenarios:
- **Weights Initialization**: For linear regression models or basic neural networks, the weight vector is typically initialized with a matrix of zeros or ones.

- **Pipeline Mocking**: Before connecting actual large-scale data, creating dummy dimensions using these functions allows you to validate the algorithm's errors and input/output dimensions.


- **Decision Boundaries & Ranges**: To plot model decision boundaries, test hyperparameters, or generate sample data, you need numbers with specific spacing or random values ​​(using `arange` and `linspace`).

## Concepts and key Functions
### np.zeros & np.ones

These functions generate matrices with all elements equal to zero or one. They accept the matrix shape as a (rows, cols) tuple:

- **np.zeros((3, 4))** creates a matrix with 3 rows and 4 columns filled with zeros.

- The `dtype` parameter defaults to `float64`, but it can be changed to `float32` for optimization.

### np.arange
It is similar to Python's built-in `range` function, but its output is a NumPy array: $$\text{np.arange(start, stop, step)}$$

- It includes the start point but excludes the stop point.

- Unlike Python's `range`, the step can be a floating-point number.

## Code Example

In [4]:
import numpy as np

# 1. Initializing matrices with zeros and ones
# Commonly used for baseline weights and dummy inputs
zero_matrix = np.zeros((3, 4), dtype=np.float32)
print("Zero Matrix (3x4):")
print(zero_matrix)

one_vector = np.ones(5, dtype=np.int32)
print("\nOne Vector (Length 5):")
print(one_vector)

# 2. Sequence generation using np.arange
# Generates numbers from 0 up to (excluding) 10 with a step size of 2
step_array = np.arange(0, 10, 2)
print("\nSequence using np.arange (step=2):")
print(step_array)

# 3. Evenly spaced numbers using np.linspace
# Generates 5 values evenly distributed between 0 and 1
linear_points = np.linspace(0, 1, 5)
print("\nPoints using np.linspace (5 values between 0 and 1):")
print(linear_points)

# 4. Combining creation routines with reshaping
# Generates a synthetic feature matrix with 6 samples and 2 features
mock_features = np.arange(12, dtype=np.float32).reshape(6, 2)
print("\nSynthetic Feature Matrix (6 samples, 2 features):")
print(mock_features)

Zero Matrix (3x4):
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

One Vector (Length 5):
[1 1 1 1 1]

Sequence using np.arange (step=2):
[0 2 4 6 8]

Points using np.linspace (5 values between 0 and 1):
[0.   0.25 0.5  0.75 1.  ]

Synthetic Feature Matrix (6 samples, 2 features):
[[ 0.  1.]
 [ 2.  3.]
 [ 4.  5.]
 [ 6.  7.]
 [ 8.  9.]
 [10. 11.]]


## Practice
### Problem Statement:

1- Create a 4x3 matrix of zeros with the `float32` data type (treat this matrix as the initial values ​​for model coefficients).

2- Using the `np.linspace` function, generate a 1D vector containing 20 evenly spaced values ​​between 0 and 100 (these data represent test inputs for a sensor).

3- Use the `reshape` method to convert this 20-element vector into a 2D matrix with dimensions (20, 1) to prepare the input for Scikit-learn.

4- Check the `shape`, `ndim`, and `dtype` attributes of the final data using a print statement.

In [18]:
import numpy as pd

# Task 1: Create a 4x3 zero matrix with float32

# Task 2: Generate 20 evenly spaced sensor inputs between 0 and 100

# Task 3: Reshape for Scikit-Learn input (20 samples, 1 feature)

# Task 4: Verify structure

## Answer is: 

In [8]:
import numpy as np

# Task 1: Create a 4x3 zero matrix with float32
initial_weights = np.zeros((4, 3), dtype=np.float32)
print("Initial Weights Matrix:")
print(initial_weights)
print("Shape:", initial_weights.shape)
print("Data Type:", initial_weights.dtype)

# Task 2: Generate 20 evenly spaced sensor inputs between 0 and 100
sensor_inputs = np.linspace(0, 100, 20)
print("\nSensor Inputs (1D):")
print(sensor_inputs)
print("Initial Shape:", sensor_inputs.shape)

# Task 3: Reshape for Scikit-Learn input (20 samples, 1 feature)
X_sensor = sensor_inputs.reshape(-1, 1)
print("\nReshaped Feature Matrix (X_sensor):")
print(X_sensor)

# Task 4: Verify structure
print("\nFinal Matrix Shape:", X_sensor.shape)
print("Dimensions (ndim):", X_sensor.ndim)
print("Data Type:", X_sensor.dtype)

Initial Weights Matrix:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Shape: (4, 3)
Data Type: float32

Sensor Inputs (1D):
[  0.           5.26315789  10.52631579  15.78947368  21.05263158
  26.31578947  31.57894737  36.84210526  42.10526316  47.36842105
  52.63157895  57.89473684  63.15789474  68.42105263  73.68421053
  78.94736842  84.21052632  89.47368421  94.73684211 100.        ]
Initial Shape: (20,)

Reshaped Feature Matrix (X_sensor):
[[  0.        ]
 [  5.26315789]
 [ 10.52631579]
 [ 15.78947368]
 [ 21.05263158]
 [ 26.31578947]
 [ 31.57894737]
 [ 36.84210526]
 [ 42.10526316]
 [ 47.36842105]
 [ 52.63157895]
 [ 57.89473684]
 [ 63.15789474]
 [ 68.42105263]
 [ 73.68421053]
 [ 78.94736842]
 [ 84.21052632]
 [ 89.47368421]
 [ 94.73684211]
 [100.        ]]

Final Matrix Shape: (20, 1)
Dimensions (ndim): 2
Data Type: float64
